### ISSUE TITLE
Typo in the wrapper

### ISSUE THREAD

**Issue by williamdes** [deepin-community/thunderbird#2]
https://github.com/deepin-community/thunderbird/blob/7edb4cab2c336dcbd266c5aecbcb356f1106713d/debian/thunderbird-wrapper-helper.sh#L412

"from the ommand line" -> "from the command line"
```[tasklist]
### Tasks
```

**Comment by williamdes** [comment]
Forwarded https://salsa.debian.org/mozilla-team/thunderbird/-/commit/d0cbb66a18ce86aa84e8887b95dab841bd86fcb3

**Comment by williamdes** [comment]
@UTsweetyfish I am closing this as I guess you will import my change from Debian

**Comment by UTsweetyfish** [comment]
> @UTsweetyfish I am closing this as I guess you will import my change from Debian

Thank you!
